cd\
cd Yam\dist
main.exe check-size "D:\Accounting"
main.exe check-size "D:\adel lamlum"
main.exe check-size "D:\Admin Intenal"
main.exe check-size "D:\Admin Mamngment"
main.exe check-size "D:\Administration"
main.exe check-size "D:\available stocks"
main.exe check-size "D:\Bank"
main.exe check-size "D:\Control Room"
main.exe check-size "D:\Customs"
main.exe check-size "D:\data-spareparts"
main.exe check-size "D:\FinanceMngt"
main.exe check-size "D:\fin-cda"
main.exe check-size "D:\FinITCtrl"
main.exe check-size "D:\fin-ware"
main.exe check-size "D:\Fleet-Dept"
main.exe check-size "D:\General"
main.exe check-size "D:\hr"
main.exe check-size "D:\it"
main.exe check-size "D:\Logistic_Plant"
main.exe check-size "D:\Logistic-Sayed"
main.exe check-size "D:\Mem"
main.exe check-size "D:\Motaz"
main.exe check-size "D:\proudction"
main.exe check-size "D:\Public"
main.exe check-size "D:\Pur2"
main.exe check-size "D:\purchaseing"
main.exe check-size "D:\purchasing - m"
main.exe check-size "D:\purchasing_a"
main.exe check-size "D:\q_lab"
main.exe check-size "D:\sd"
main.exe check-size "D:\SDreports"
main.exe check-size "D:\sms_abo"
main.exe check-size "D:\sms_site"
main.exe check-size "D:\SMS_SUIAgent"
main.exe check-size "D:\Spare Parts DB"
main.exe check-size "D:\Spareparts"
main.exe check-size "D:\tarek shtewi"
main.exe check-size "D:\tc data"
main.exe check-size "D:\time attandance"
main.exe check-size "D:\Users"
main.exe check-size "D:\Warehouse_Plant"
main.exe check-size "D:\West Tripoli Area"