cd\
cd Yam\dist
py main.py scan "D:\Accounting"
py main.py scan "D:\adel lamlum"
py main.py scan "D:\Admin Intenal"
py main.py scan "D:\Admin Mamngment"
py main.py scan "D:\Administration"
py main.py scan "D:\available stocks"
py main.py scan "D:\Bank"
py main.py scan "D:\Control Room"
py main.py scan "D:\Customs"
py main.py scan "D:\data-spareparts"
py main.py scan "D:\FinanceMngt"
py main.py scan "D:\fin-cda"
py main.py scan "D:\FinITCtrl"
py main.py scan "D:\fin-ware"
py main.py scan "D:\Fleet-Dept"
py main.py scan "D:\General"
py main.py scan "D:\hr"
py main.py scan "D:\it"
py main.py scan "D:\Logistic_Plant"
py main.py scan "D:\Logistic-Sayed"
py main.py scan "D:\Mem"
py main.py scan "D:\Motaz"
py main.py scan "D:\proudction"
py main.py scan "D:\Public"
py main.py scan "D:\Pur2"
py main.py scan "D:\purchaseing"
py main.py scan "D:\purchasing - m"
py main.py scan "D:\purchasing_a"
py main.py scan "D:\q_lab"
py main.py scan "D:\sd"
py main.py scan "D:\SDreports"
py main.py scan "D:\sms_abo"
py main.py scan "D:\sms_site"
py main.py scan "D:\SMS_SUIAgent"
py main.py scan "D:\Spare Parts DB"
py main.py scan "D:\Spareparts"
py main.py scan "D:\tarek shtewi"
py main.py scan "D:\tc data"
py main.py scan "D:\time attandance"
py main.py scan "D:\Users"
py main.py scan "D:\Warehouse_Plant"
py main.py scan "D:\West Tripoli Area"